name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {} 

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read

    env:
      APP_URL: "https://disastertweetclassifier.streamlit.app/"

    steps:
      - name: Ping app (with built-in curl retry)
        run: |
          # --fail: make curl exit non-zero on HTTP errors
          # --show-error: print errors
          # --silent: reduce noise
          # --retry/--retry-delay/--retry-all-errors: robust against transient failures
          curl --fail --show-error --silent \
               --retry 5 --retry-delay 10 --retry-all-errors \
               -o /dev/null "$APP_URL"

      - name: Log timestamp (UTC)
        run: date -u
